import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { ArtifactManifest, RunConfig } from '../core/types.js';
import type { RunState } from '../core/state.js';
import { listArtifacts } from '../storage/artifacts.js';
import { atomicJson, redact } from '../storage/journal.js';
export interface RunMetadata { run_id:string;data_origin:'real'|'demo';recipe_version:string;started_at:string;deadline_at:string;config:RunConfig;identity:string|null;source_commit:string|null;plan:{unit:string;stage:string}[]; }
export const escapeHtml=(s:string):string=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const escapeMarkdown=(s:string):string=>s.replace(/[\\`*_{}\[\]<>!#|]/gu,'\\$&').replace(/[\r\n]+/gu,' ');
export function quotaReceipt(state:RunState){
  const record=(value:unknown):value is Record<string,unknown>=>!!value&&typeof value==='object'&&!Array.isArray(value);
  const number=(value:unknown,min:number,max=Number.MAX_SAFE_INTEGER)=>typeof value==='number'&&Number.isFinite(value)&&value>=min&&value<=max?value:null;
  const text=(value:unknown)=>typeof value==='string'?String(redact(value)).slice(0,200):null;
  const raw=state.quota;const observed=raw?number(raw.observedAt,0,8.64e15):null;
  const buckets=raw&&Array.isArray(raw.buckets)?raw.buckets.filter(record).slice(0,128).map(bucket=>({limit_id:text(bucket.limitId),limit_name:text(bucket.limitName),windows:Array.isArray(bucket.windows)?bucket.windows.filter(record).slice(0,20).map(window=>({name:text(window.name),remaining_percent:number(window.remainingPercent,0,100),used_percent:number(window.usedPercent,0,100),window_duration_minutes:number(window.windowDurationMins,1),resets_at_unix_seconds:number(window.resetsAt,1)})):[]})):[];
  return {status:raw?state.quotaStatus:'unavailable',source:raw?text(raw.source):null,observed_at:observed===null?null:new Date(observed).toISOString(),buckets,note:'Account-wide observation; changes may include other sessions. Windows are independent and are never summed. Local thresholds are not billing caps.'};
}
export async function harvest(runDir:string,state:RunState,meta:RunMetadata):Promise<string> {
  const artifacts=await listArtifacts(runDir); const destination=join(runDir,'harvest'); await mkdir(destination,{recursive:true,mode:0o700});
  const accepted=new Set(artifacts.map(a=>a.unit_id));
  const quota=quotaReceipt(state);
  const receipt={schema_version:'1.0',run_id:meta.run_id,data_origin:meta.data_origin,recipe_id:meta.config.recipe_id,recipe_version:meta.recipe_version,source_commit:meta.source_commit,started_at:meta.started_at,ended_at:state.endedAt,deadline_at:meta.deadline_at,status:state.status,stop_reason:state.stopReason,dispatch_intents:state.dispatches,workers_started:state.startedWorkers,failed_attempts:Object.values(state.attempts).filter(a=>['rejected','quarantined','interrupted'].includes(a.status)),usage_completeness:state.usage.length===state.startedWorkers&&state.startedWorkers>0&&state.usage.every(u=>u.completeness==='complete'||u.usage_completeness==='complete')?'complete':'partial',usage:state.usage,quota,logical_artifacts:new Set(artifacts.map(a=>a.logical_key)).size,artifacts,unfinished_plan:meta.plan.filter(p=>!accepted.has(p.unit)),human_review:'pending'};
  await atomicJson(join(destination,'receipt.json'),receipt);
  const lines=[`# BeforeTibo harvest — ${meta.data_origin.toUpperCase()}`,`Run: ${meta.run_id}`,`Recipe: ${meta.config.recipe_id} ${meta.recipe_version}`,`Source snapshot: ${meta.source_commit??'unavailable'}`,`Started: ${meta.started_at}; ended: ${state.endedAt??'unavailable'}`,`Original deadline: ${meta.deadline_at}`,`State: ${state.status}`,`Stop reason: ${escapeMarkdown(state.stopReason??'plan complete')}`,`Dispatch intents: ${state.dispatches}; confirmed workers: ${state.startedWorkers}`,`Usage coverage: ${receipt.usage_completeness}. Quota: ${escapeMarkdown(quota.status)}.`,`Account changes can include other sessions; local limits are not billing caps.`,`Human review: pending.`, '',`Quota source: ${escapeMarkdown(quota.source??'unavailable')}; observed: ${quota.observed_at??'unavailable'}.`,...quota.buckets.flatMap(bucket=>bucket.windows.map(window=>`- ${escapeMarkdown(bucket.limit_id??'unknown')}/${escapeMarkdown(window.name??'unknown')}: ${window.remaining_percent===null?'unavailable':`${window.remaining_percent}% remaining`}; window ${window.window_duration_minutes??'unavailable'} minutes; reset ${window.resets_at_unix_seconds??'unavailable'} Unix seconds.`)),''];
  for(const a of artifacts){lines.push(`## ${escapeMarkdown(String(redact(a.title)))}`,`Kind: ${a.kind}. Adoption: ${a.adoption}.`,...a.validations.map(v=>`- ${v.id}: ${v.status} — ${escapeMarkdown(String(redact(v.summary)))}`),...a.files.map(f=>`- [${escapeMarkdown(f.path)}](../artifacts/${a.artifact_id}/${f.path.split('/').map(encodeURIComponent).join('/')})`),...a.limitations.map(l=>`- Limitation: ${escapeMarkdown(String(redact(l)))}`),'');}
  lines.push('## Failed / interrupted exploration',...receipt.failed_attempts.map(a=>`- ${a.unit}: ${a.status}`),'## Unfinished plan',...receipt.unfinished_plan.map(p=>`- ${p.unit}`));
  await writeFile(join(destination,'SUMMARY.md'),lines.join('\n')+'\n',{mode:0o600});
  const sections=await Promise.all(artifacts.map(async(a:ArtifactManifest)=>{
    const previews:string[]=[];
    for(const f of a.files.filter(f=>f.path.endsWith('.md'))){const text=await readFile(join(runDir,'artifacts',a.artifact_id,f.path),'utf8');previews.push(`<details><summary>${escapeHtml(f.path)}</summary><pre>${escapeHtml(text)}</pre></details>`);}
    return `<article><h2>${escapeHtml(a.title)}</h2><p>${escapeHtml(a.kind)} · ${escapeHtml(a.status)} · Human review pending</p><ul>${a.validations.map(v=>`<li>${escapeHtml(v.id)}: ${escapeHtml(v.status)} — ${escapeHtml(v.summary)}</li>`).join('')}</ul>${previews.join('')}<p>Generated executable tools are separate files. Open them only after review.</p><ul>${a.files.map(f=>`<li><a href="../artifacts/${encodeURIComponent(a.artifact_id)}/${f.path.split('/').map(encodeURIComponent).join('/')}" rel="noreferrer">${escapeHtml(f.path)}</a></li>`).join('')}</ul></article>`;
  }));
  const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src 'none'; base-uri 'none'; form-action 'none'"><title>BeforeTibo · ${meta.data_origin.toUpperCase()} harvest</title><style>body{font:16px/1.6 system-ui;max-width:1000px;margin:3rem auto;padding:0 1rem;background:#111827;color:#e5e7eb}a{color:#93c5fd}article{padding:1.2rem;margin:1rem 0;border:1px solid #374151;border-radius:12px}pre{white-space:pre-wrap;overflow-wrap:anywhere}summary{cursor:pointer}.badge{color:#fbbf24}</style><header><p class="badge">${meta.data_origin.toUpperCase()} · ${escapeHtml(state.status)}</p><h1>BeforeTibo harvest</h1><p>${escapeHtml(meta.config.recipe_id)} · ${receipt.logical_artifacts} logical artifacts · ${state.dispatches} dispatch intents</p><p>Usage: ${receipt.usage_completeness} · quota ${escapeHtml(quota.status)} · review pending</p></header>${sections.join('')}<h2>Account quota observation</h2><pre>${escapeHtml(JSON.stringify(quota,null,2))}</pre><h2>Run record</h2><pre>${escapeHtml(lines.slice(0,13).join('\n'))}</pre><h2>Unfinished / failed</h2><pre>${escapeHtml(JSON.stringify({unfinished:receipt.unfinished_plan,failures:receipt.failed_attempts},null,2))}</pre></html>`;
  await writeFile(join(destination,'index.html'),html,{mode:0o600});return join(destination,'index.html');
}
export async function exportSummary(runDir:string,output:string):Promise<void> {
  // Public export deliberately excludes artifact content: a generated guide or patch can contain private source.
  const receipt=JSON.parse(await readFile(join(runDir,'harvest','receipt.json'),'utf8')) as {data_origin:string;recipe_id:string;status:string;dispatch_intents:number;artifacts:ArtifactManifest[]};
  await mkdir(output,{recursive:false,mode:0o700});
  const clean={schema_version:'1.0',data_origin:receipt.data_origin,recipe_id:receipt.recipe_id,status:receipt.status,dispatch_intents:receipt.dispatch_intents,artifacts:receipt.artifacts.map(a=>({kind:a.kind,status:a.status,adoption:a.adoption,checks:a.validations.map(v=>({id:v.id,status:v.status}))})),excluded:'Source, generated content, paths, identities, raw logs, quota history and credentials are excluded.'};
  await atomicJson(join(output,'receipt.json'),clean);await writeFile(join(output,'README.md'),'# BeforeTibo sanitized export\n\n'+JSON.stringify(clean,null,2)+'\n',{mode:0o600});
}
